name: Windows Release Build

on:
  # push:
  #   tags:
  #     - 'v*' # Triggers when you push a tag like v1.0.0
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    env:
      MIX_ENV: prod
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up Elixir
      uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93
      with:
        elixir-version: '1.17'
        otp-version: '27'

    - name: Install Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.13.0

    - name: Install XZ and 7zip
      run: |
        choco install 7zip -y

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-

    - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install dependencies and build app
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix compile
        mix assets.deploy 
        mix ex_tauri.build

    - name: Package Release
      shell: pwsh
      run: |
        # Replace 'your_app_name' with your actual app name from mix.exs
        Compress-Archive -Path src-tauri/target/release/bundle/* -DestinationPath record_verifier-windows.zip

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: record_verifier-windows.zip
